---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
spec:
  template:
    spec:
      containers:
      - name: kafka-tools
        image: confluentinc/cp-kafka:7.4.4
        command:
        - /bin/bash
        - -c
        - |
          kafka-topics --create --topic test-topic --bootstrap-server kafka-service:9092 --partitions 3 --replication-factor 1
          kafka-topics --create --topic logs-topic --bootstrap-server kafka-service:9092 --partitions 3 --replication-factor 1
          echo "Topics created successfully"
      restartPolicy: OnFailure