apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: kafka-namespace
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: external
      port: 32004        # cổng service trong cluster (không quan trọng bằng targetPort)
      targetPort: 32004  # phải khớp containerPort listener EXTERNAL trong Pod
      nodePort: 32004    # cổng public trên node (30000-32767)